package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"JobVacancyManagement/database"
	"JobVacancyManagement/graph/model"
	"context"
)

// CreateJobDescription is the resolver for the createJobDescription field.
func (r *mutationResolver) CreateJobDescription(ctx context.Context, input model.JobDescriptionCreationInput) (*model.JobDescription, error) {
	return db.CreateJobDescription(input), nil
}

// UpdateJobDescription is the resolver for the updateJobDescription field.
func (r *mutationResolver) UpdateJobDescription(ctx context.Context, id string, input model.JobDescriptionUpdateInput) (*model.JobDescription, error) {
	return db.UpdateJobDescription(id, input), nil
}

// DeleteJobDescription is the resolver for the deleteJobDescription field.
func (r *mutationResolver) DeleteJobDescription(ctx context.Context, id string) (*model.JobDescriptionDeleteResponse, error) {
	return db.DeleteJobDescription(id), nil
}

// JobDescriptions is the resolver for the jobDescriptions field.
func (r *queryResolver) JobDescriptions(ctx context.Context) ([]*model.JobDescription, error) {
	return db.GetJobDescriptions(), nil
}

// JobDescription is the resolver for the jobDescription field.
func (r *queryResolver) JobDescription(ctx context.Context, id string) (*model.JobDescription, error) {
	return db.GetJobDescription(id), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
var db = database.Connect()
