// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type JobDescription struct {
	ID                string   `json:"_id"`
	PositionName      string   `json:"positionName"`
	YearsOfExperience int      `json:"yearsOfExperience"`
	Skills            []string `json:"skills"`
	MinSalary         int      `json:"minSalary"`
	Active            bool     `json:"active"`
}

type JobDescriptionCreationInput struct {
	PositionName      string   `json:"positionName"`
	YearsOfExperience int      `json:"yearsOfExperience"`
	Skills            []string `json:"skills"`
	MinSalary         int      `json:"minSalary"`
	Active            bool     `json:"active"`
}

type JobDescriptionDeleteResponse struct {
	DeletedJobDescriptionID string `json:"deletedJobDescriptionID"`
}

type JobDescriptionUpdateInput struct {
	PositionName      *string  `json:"positionName,omitempty"`
	YearsOfExperience *int     `json:"yearsOfExperience,omitempty"`
	Skills            []string `json:"skills,omitempty"`
	MinSalary         *int     `json:"minSalary,omitempty"`
	Active            *bool    `json:"active,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
